R-highs: update to 1.10.0-1

diff --git a/R/R-highs/files/patch-use-Macports-highs.diff b/R/R-highs/files/patch-use-Macports-highs.diff
--- a/R/R-highs/files/patch-use-Macports-highs.diff
+++ b/R/R-highs/files/patch-use-Macports-highs.diff
@@ -1,6 +1,6 @@
---- configure	2025-01-08 16:58:26.000000000 +0800
-+++ configure	2025-01-15 04:02:04.000000000 +0800
-@@ -1,17 +1,7 @@
+--- configure	2025-04-21 02:28:36.000000000 +0800
++++ configure	2025-04-26 01:58:31.000000000 +0800
+@@ -1,27 +1,12 @@
  #!/bin/sh
  
  echo "Use 'configure'"
@@ -12,10 +12,20 @@
 -    cd ${R_HIGHS_PKG_HOME}
 -    rm -rf inst/HiGHS
 -    R_HIGHS_LIB_DIR=${R_HIGHS_PKG_HOME}/src/highslib
--    # cp -r ${R_HIGHS_LIB_DIR} /home/f/lib/  # development
+-    
+-    # development
+-    # rm -rf /home/f/lib/highslib
+-    # cp -rf ${R_HIGHS_LIB_DIR} /home/f/lib/
 -fi
--
+ 
 +export R_HIGHS_LIB_DIR=@PREFIX@
  
  sed -e "s|@RHIGHS_LIB_DIR@|$R_HIGHS_LIB_DIR|g" src/Makevars.in > src/Makevars
  
+-
+ if [ -z "$(ls ${R_HIGHS_LIB_DIR} | grep 'include')" ]; then
+     echo "'HiGHS' libraries could not be found!"
+     exit 1
+ fi
+-
+-
